### ISSUE TITLE
Try setting RPATH (avoid need of: export DYLD_LIBRARY_PATH)

### ISSUE THREAD

**Issue by kimwalisch** [kimwalisch/homebrew-primecount#1]
* https://discourse.paraview.org/t/macos-linking-application-with-paraview-libraries-and-not-depending-on-dyld-library-path/6413/5

> Yes the option using ... makes the tree non-relocatable, this is only for a fixed install in, say, /opt/local or /usr/local.

```
  set(CMAKE_INSTALL_NAME_DIR "@rpath")
  set(CMAKE_INSTALL_RPATH "@loader_path/../lib")  # self relative LIBDIR
  set(CMAKE_SKIP_INSTALL_RPATH FALSE)          # don't skip the full RPATH for the install tree
```

Maybe this could be set using: ```cmake . -DCMAKE_INSTALL_NAME_DIR="@rpath" -DCMAKE_INSTALL_RPATH="@loader_path/../lib" -DCMAKE_SKIP_INSTALL_RPATH=FALSE```. This could potentially fix libprimecount.so not found if the user has not set DYLD_LIBRARY_PATH="/usr/opt/..."

**Comment by dimpase** [comment]
If I install primecount on macOS using Homebrew, using the defaut instructions, all seems to work as it is now.

**Comment by kimwalisch** [comment]
@dimpase By luck I have figured out how to use the default AppleClang C/C++ compiler with OpenMP today. Therefore I have just done a new release of homebrew-primecount with this change. The primecount installation time using homebrew has now been significantly reduced as homebrew's LLVM/Clang does not need to be downloaded + installed anymore.

I also think that I have fixed the ```RPATH``` issue. I am now using the ```-DCMAKE_INSTALL_RPATH=#{rpath}``` option that is also used by the core packages provided by homebrew (e.g.: https://github.com/Homebrew/homebrew-core/blob/master/Formula/primesieve.rb#L20)

I have tested the new primecount version on both an Intel Mac (macOS 11.6) and an Apple Silicon Mac (macOS 12.1) and it worked fine for me.

**Comment by dimpase** [comment]
Should you try putting primecount in Homebrew's core, too?

**Comment by kimwalisch** [comment]
I tried submitting primecount to homebrew about 5 years ago and it was rejected because primecount was not notable enough. If I remember correctly they required 100 GitHub stars & 30 people watching the repo on GitHub (primecount currently only has 20 watchers). It is difficult for primecount to meet the high [homebrew minimum requirements](https://docs.brew.sh/Versions):

> Versioned formulae submitted should be expected to be used by a large number of people. If this ceases to be the case, they will be removed. We will aim not to remove those in the top 3,000 install_on_request formulae.

Because of this primecount is currently only a homebrew tap.

**Comment by dimpase** [comment]
They don't have GH stars and watchers requirements any more, as far as I see. Perhaps, one should wait until primecount makes it into Debian (it's almost there).

**Comment by kimwalisch** [comment]
OK, I'll try to submit it again to homebrew/core once it is in Debian.

**Comment by kimwalisch** [comment]
> Should you try putting primecount in Homebrew's core, too?

@dimpase primecount is now a homebrew-core formula, see: https://github.com/Homebrew/homebrew-core/blob/master/Formula/primecount.rb. Hence primecount can now be installed using ```brew install primecount``` on macOS.

**Comment by dimpase** [comment]
Thanks, we're adding this on https://trac.sagemath.org/ticket/33805
